import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/header";
import FooterComponent from "./components/footer";
import ContactWP from "./assets/whatsapp";
import { ThemeProvider } from './context/ThemeProvider';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Samuel Proença - Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg", // Certifique-se de que o icon.svg está na raiz de /app
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <HeaderComponent />
          {children}
          <ContactWP />
          <FooterComponent />
        </ThemeProvider>
      </body>
    </html>
  );
}
