`use client`;
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/header";
import FooterComponent from "./components/footer";
import ContactWP from "./assets/whatsapp";
import { ThemeProvider } from "next-themes";
import FallingLeaves from "./components/FallingLeaves";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Samuel Proença - Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg", // Certifique-se de que o icon.svg está na raiz de /app
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative overflow-hidden">
        

        {/* Conteúdo */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <HeaderComponent />
          <main className="relative z-10">
            {children}
          </main>
          <ContactWP />
          <FooterComponent />
        </ThemeProvider>
      </body>
    </html>
  );
}