`use client`;
import type { Metadata } from "next";
import "./globals.css";
import ContactWP from "./assets/whatsapp";
import { ThemeProvider } from "next-themes";


export const metadata: Metadata = {
  title: "Samuel Proença - Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg", // Certifique-se de que o icon.svg está na raiz de /app
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="relative overflow-hidden">
        

        {/* Conteúdo */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="relative z-10">
            {children} 
          </main>
          <ContactWP />
        </ThemeProvider>
      </body>
    </html>
  );
}
